name: Dart Web CI/CD

on:
  push:
    branches: [ web-ci ]

jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{ secrets.ANDROID_CI_KEY }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: beta
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web --release
    -run: |
      cd build/web
      git init
      git config --global user.email fanzheyuan@zheyuan.fun
      git config --global user.name fanzheyuan
      git status
      git remote add origin https://${{ secrets.ANDROID_CI_KEY }}@github.com/fansvideo/fansvideo.git
      git checkout -b gh-pages
      git commit -m 'update pages'
      git push origin gh-pages -f
